# -*- coding: utf-8 -*-
"""csvtodata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UXL13boqAyCq0zVcp2UkOOKDuXpDpf9V
"""

!pip install -q tensorflow-ranking

from typing import Dict, Tuple
import tensorflow as tf
import tensorflow_ranking as tfr
import pandas as pd
import numpy as np

data = pd.read_csv('ratings_Beauty.csv')

data.head()

dataset = tf.data.experimental.make_csv_dataset('ratings_Beauty.csv', batch_size=1000)
iterator = dataset.as_numpy_iterator()

dataset = dataset.map(lambda x: {
    "UserId": x["UserId"],
    "ProductId": x["ProductId"],
    "Rating": x["Rating"]
})

users = dataset.map(lambda x: x["UserId"])
prod = dataset.map(lambda x: x["ProductId"])