# -*- coding: utf-8 -*-
"""LTRMS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Trm0WAGYtVP1J2Gg3ZZ-_W5hfplWrQbG
"""

!pip install -q tensorflow-ranking
!pip install -q --upgrade tfds-nightly

import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_ranking as tfr

# Load MSLR-WEB10K dataset from TFDS.
ds = tfds.load("mslr_web/10k_fold1", split="train")

# Add a mask tensor.
ds = ds.map(lambda feature_map: {
    "_mask": tf.ones_like(feature_map["label"], dtype=tf.bool),
    **feature_map
})

# Shuffle data and create padded batches for queries with different lengths.
# Padded items will have False on `_mask`.
ds = ds.shuffle(buffer_size=1000).padded_batch(batch_size=32)

# Create (features, labels) tuples from data and set -1 label for masked items.
ds = ds.map(lambda feature_map: (
    feature_map, tf.where(feature_map["_mask"], feature_map.pop("label"), -1.)))

# Create a model with Keras Functional API.
inputs = {
    name: tf.keras.Input(shape=(None, 1), dtype=tf.float32, name=name)
    for name in ds.element_spec[0]
    if name != "_mask"
}
norm_inputs = [tf.keras.layers.BatchNormalization()(x) for x in inputs.values()]
x = tf.concat(norm_inputs, axis=-1)
for layer_width in [128, 64, 32]:
  x = tf.keras.layers.Dense(units=layer_width)(x)
  x = tf.keras.layers.Activation(activation=tf.nn.relu)(x)
scores = tf.squeeze(tf.keras.layers.Dense(units=1)(x), axis=-1)

# Create, compile and train the model.
model = tf.keras.Model(inputs=inputs, outputs=scores)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    loss=tfr.keras.losses.SoftmaxLoss(),
    metrics=tfr.keras.metrics.get("ndcg", topn=5, name="NDCG@5"))
model.fit(ds, epochs=3)